apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ns2
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0b43d5726c2822dce::fsap-0c9cdabf1ea1ae60f"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ns2-1
  namespace: ns2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  # match storageClassName with PV above (leave blank to match PV with no storage class)
  storageClassName: ""
  volumeName: pv-ns2