apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-pv-background-access
rules:
- apiGroups: [""]
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-pv-background-access
subjects:
- kind: ServiceAccount
  name: kyverno-background-controller
  namespace: kyverno
roleRef:
  kind: ClusterRole
  name: kyverno-pv-background-access
  apiGroup: rbac.authorization.k8s.io
