apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ns1
  labels:
    pv.kubernetes.io/allowed-namespace: ns1
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0b6958d6cf675d80e::fsap-07ee4d4d240411d5a"
    readOnly: false

---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-ns1-1
#   namespace: ns1
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 200Mi
#   storageClassName: ""
#   volumeName: pv-ns1
# ---

# apiVersion: kyverno.io/v1
# kind: ClusterPolicy
# metadata:
#   name: restrict-pv-binding-by-namespace
# spec:
#   validationFailureAction: Enforce
#   background: false
#   rules:
#     - name: validate-pv-claim-namespace

#       match:
#         resources:
#           kinds:
#             - PersistentVolume

#       preconditions:
#         # - key: "{{ request.object.spec.claimRef.namespace }}"
#         #   operator: NotEquals
#         #   value: ""

#         - key: "{{ request.object.metadata.labels.\"pv.kubernetes.io/allowed-namespace\" }}"
#           operator: NotEquals
#           value: ""

#       validate:
#         message: >-
#           PV is restricted to namespace
#           '{{ request.object.metadata.labels."pv.kubernetes.io/allowed-namespace" }}'
#         pattern:
#           spec:
#             claimRef:
#               namespace: "{{ request.object.metadata.labels.\"pv.kubernetes.io/allowed-namespace\" }}"

