apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ns1-1
  namespace: ns1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: ""
  volumeName: pv-ns1
